#!/Users/divinejohns/memU/venv/bin/python
import sys
from aider_install.main import install_aider
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(install_aider())
