# IZA OS Chat Integration Configuration
# Enterprise-grade configuration following McKinsey 7S framework

# Lobe Chat Configuration
lobe_chat:
  api_url: "https://api.lobe.chat/v1"
  api_key: "${LOBE_CHAT_API_KEY}"
  model: "lobe-chat"
  max_tokens: 4000
  temperature: 0.7
  timeout: 30
  retry_attempts: 3
  retry_delay: 1.0

# Claude Configuration
claude:
  api_key: "${CLAUDE_API_KEY}"
  model: "claude-3-sonnet-20240229"
  max_tokens: 4000
  temperature: 0.7
  timeout: 30

# OpenAI Configuration
openai:
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4"
  max_tokens: 4000
  temperature: 0.7
  timeout: 30

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: "${REDIS_PASSWORD}"
  max_connections: 20
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true

# Database Configuration
database:
  url: "postgresql://iza_user:iza_pass@localhost/iza_os_chat"
  pool_size: 20
  max_overflow: 30
  pool_timeout: 30
  pool_recycle: 3600
  echo: false

# Security Configuration
security:
  jwt_secret: "${JWT_SECRET}"
  jwt_algorithm: "HS256"
  jwt_expiry_hours: 24
  encryption_key: "${ENCRYPTION_KEY}"
  rate_limit_per_minute: 60
  max_message_length: 4000
  content_filter_enabled: true

# Monitoring Configuration
monitoring:
  metrics_enabled: true
  metrics_port: 8001
  log_level: "INFO"
  log_format: "json"
  health_check_interval: 30
  performance_monitoring: true

# Cache Configuration
cache:
  conversation_ttl: 3600  # 1 hour
  session_ttl: 86400      # 24 hours
  max_cache_size: 10000
  cache_cleanup_interval: 300

# Business Logic Configuration
business:
  max_conversations_per_user: 100
  max_messages_per_conversation: 1000
  auto_archive_after_days: 30
  cost_tracking_enabled: true
  usage_analytics_enabled: true

# Integration Configuration
integrations:
  azis_learns_ai:
    enabled: true
    endpoint: "http://localhost:8002"
    api_key: "${AZI_LEARNS_API_KEY}"
    
  agentx_interface:
    enabled: true
    endpoint: "http://localhost:8003"
    api_key: "${AGENTX_API_KEY}"
    
  ai_workflow:
    enabled: true
    endpoint: "http://localhost:8004"
    api_key: "${AI_WORKFLOW_API_KEY}"

# Quality Gates Configuration
quality_gates:
  test_coverage_minimum: 90
  performance_threshold_ms: 200
  error_rate_threshold: 0.01
  availability_threshold: 99.9
  security_scan_enabled: true

# Compliance Configuration
compliance:
  gdpr_enabled: true
  data_retention_days: 365
  audit_logging: true
  encryption_at_rest: true
  encryption_in_transit: true
  access_logging: true
