# Governance configuration for IZA OS Enterprise Platform
# Wyoming LLC compliance rules and audit settings

governance:
  # General governance settings
  service_name: "iza-os-governance"
  compliance_framework: "wyoming_llc"
  audit_frequency_days: 90
  
  # Compliance configuration
  compliance:
    enabled: true
    framework: "wyoming_llc"
    
    # Wyoming LLC compliance rules
    wyoming_llc_rules:
      business_registration:
        enabled: true
        requirements:
          - "Valid Wyoming LLC registration certificate"
          - "Current registered agent information"
          - "Annual report filing compliance"
          - "Business license validity"
        validation_criteria:
          registration_certificate_valid: true
          registered_agent_current: true
          annual_report_current: true
          business_license_valid: true
        severity: "critical"
        cooldown_minutes: 1
      
      tax_compliance:
        enabled: true
        requirements:
          - "Federal tax ID (EIN) registration"
          - "State tax registration"
          - "Quarterly tax filings"
          - "Annual tax returns"
        validation_criteria:
          ein_registered: true
          state_tax_registered: true
          quarterly_filings_current: true
          annual_returns_filed: true
        severity: "critical"
        cooldown_minutes: 1
      
      operational_compliance:
        enabled: true
        requirements:
          - "Business operations within legal scope"
          - "Employee compliance (if applicable)"
          - "Contract compliance"
          - "Regulatory compliance"
        validation_criteria:
          operations_legal: true
          employee_compliance: true
          contract_compliance: true
          regulatory_compliance: true
        severity: "high"
        cooldown_minutes: 5
      
      data_protection:
        enabled: true
        requirements:
          - "GDPR compliance (if applicable)"
          - "CCPA compliance (if applicable)"
          - "Data security measures"
          - "Privacy policy compliance"
        validation_criteria:
          gdpr_compliant: true
          ccpa_compliant: true
          data_security_measures: true
          privacy_policy_compliant: true
        severity: "high"
        cooldown_minutes: 5
      
      financial_reporting:
        enabled: true
        requirements:
          - "Accurate financial records"
          - "Regular financial reporting"
          - "Audit trail maintenance"
          - "Financial statement compliance"
        validation_criteria:
          financial_records_accurate: true
          regular_reporting: true
          audit_trail_maintained: true
          financial_statements_compliant: true
        severity: "medium"
        cooldown_minutes: 15
    
    # Business compliance settings
    business_compliance:
      ace_businesses_total: 382
      wyoming_llc_subsidiaries: 8
      compliance_check_interval: 24  # hours
      violation_threshold: 0
      compliance_score_threshold: 90
    
    # Compliance monitoring
    monitoring:
      enabled: true
      check_interval: 3600  # seconds (1 hour)
      alert_on_violations: true
      auto_remediation: false
      
      # Compliance categories
      categories:
        business_registration:
          enabled: true
          priority: 1
          auto_check: true
        
        tax_compliance:
          enabled: true
          priority: 1
          auto_check: true
        
        operational_compliance:
          enabled: true
          priority: 2
          auto_check: true
        
        data_protection:
          enabled: true
          priority: 2
          auto_check: true
        
        financial_reporting:
          enabled: true
          priority: 3
          auto_check: true
  
  # Audit trail configuration
  audit_trail:
    enabled: true
    retention_days: 2555  # 7 years for compliance
    
    # Audit categories
    audit_categories:
      orchestration:
        enabled: true
        log_level: "info"
        include_details: true
      
      business:
        enabled: true
        log_level: "info"
        include_details: true
      
      system:
        enabled: true
        log_level: "warning"
        include_details: true
      
      integration:
        enabled: true
        log_level: "info"
        include_details: true
      
      security:
        enabled: true
        log_level: "error"
        include_details: true
      
      compliance:
        enabled: true
        log_level: "info"
        include_details: true
    
    # Digital signature settings
    digital_signature:
      enabled: true
      algorithm: "HMAC-SHA256"
      secret_key: "${AUDIT_SECRET_KEY}"
      key_rotation_days: 90
    
    # Hash chain settings
    hash_chain:
      enabled: true
      algorithm: "SHA-256"
      verify_integrity: true
      check_interval: 3600  # seconds
    
    # Audit export settings
    export:
      enabled: true
      formats: ["json", "csv", "xml"]
      compression: true
      encryption: true
      batch_size: 1000
  
  # Risk management configuration
  risk_management:
    enabled: true
    assessment_interval: 30  # days
    
    # Risk categories
    risk_categories:
      operational:
        enabled: true
        weight: 0.25
        indicators:
          - name: "system_failures"
            threshold: 0.1
            weight: 0.3
          - name: "automation_errors"
            threshold: 0.05
            weight: 0.2
      
      business:
        enabled: true
        weight: 0.20
        indicators:
          - name: "revenue_volatility"
            threshold: 0.2
            weight: 0.4
          - name: "market_changes"
            threshold: 0.3
            weight: 0.3
      
      compliance:
        enabled: true
        weight: 0.20
        indicators:
          - name: "compliance_violations"
            threshold: 0.0
            weight: 0.5
      
      security:
        enabled: true
        weight: 0.20
        indicators:
          - name: "security_incidents"
            threshold: 0.0
            weight: 0.6
      
      financial:
        enabled: true
        weight: 0.10
        indicators:
          - name: "financial_volatility"
            threshold: 0.15
            weight: 0.4
      
      technical:
        enabled: true
        weight: 0.05
        indicators:
          - name: "technical_debt"
            threshold: 0.2
            weight: 0.3
    
    # Risk levels
    risk_levels:
      low:
        threshold: 0.4
        color: "green"
        action: "monitor"
      
      medium:
        threshold: 0.6
        color: "yellow"
        action: "review"
      
      high:
        threshold: 0.8
        color: "orange"
        action: "mitigate"
      
      critical:
        threshold: 1.0
        color: "red"
        action: "immediate_action"
    
    # Mitigation strategies
    mitigation_strategies:
      operational:
        - "Implement system redundancy and failover mechanisms"
        - "Enhance system monitoring and alerting"
        - "Improve automation testing and validation"
        - "Implement automation rollback procedures"
      
      business:
        - "Diversify revenue streams"
        - "Implement revenue forecasting and monitoring"
        - "Conduct regular market analysis"
        - "Develop market adaptation strategies"
      
      compliance:
        - "Implement automated compliance monitoring"
        - "Conduct regular compliance audits"
        - "Provide compliance training to staff"
      
      security:
        - "Implement enhanced security monitoring"
        - "Conduct security assessments and penetration testing"
        - "Update security policies and procedures"
      
      financial:
        - "Implement financial controls and monitoring"
        - "Conduct regular financial audits"
        - "Diversify financial investments"
      
      technical:
        - "Implement technical debt reduction plan"
        - "Enhance technical documentation"
        - "Conduct regular technical reviews"
  
  # Reporting configuration
  reporting:
    enabled: true
    
    # Report types
    report_types:
      compliance_report:
        enabled: true
        frequency: "monthly"
        format: "pdf"
        recipients: ["compliance@iza-os.com", "legal@iza-os.com"]
      
      audit_report:
        enabled: true
        frequency: "quarterly"
        format: "pdf"
        recipients: ["audit@iza-os.com", "compliance@iza-os.com"]
      
      risk_report:
        enabled: true
        frequency: "monthly"
        format: "pdf"
        recipients: ["risk@iza-os.com", "executive@iza-os.com"]
      
      governance_dashboard:
        enabled: true
        frequency: "real-time"
        format: "json"
        recipients: ["dashboard"]
    
    # Report templates
    templates:
      compliance_report:
        template_file: "templates/compliance_report.html"
        include_charts: true
        include_recommendations: true
      
      audit_report:
        template_file: "templates/audit_report.html"
        include_timeline: true
        include_violations: true
      
      risk_report:
        template_file: "templates/risk_report.html"
        include_mitigation: true
        include_trends: true
  
  # Dashboard integration
  dashboard:
    enabled: true
    refresh_interval: 60  # seconds
    
    # Dashboard widgets
    widgets:
      compliance_status:
        enabled: true
        widget_type: "gauge"
        data_source: "compliance_manager"
      
      audit_timeline:
        enabled: true
        widget_type: "timeline"
        data_source: "audit_trail_manager"
      
      risk_heatmap:
        enabled: true
        widget_type: "heatmap"
        data_source: "risk_manager"
      
      violation_trends:
        enabled: true
        widget_type: "line_chart"
        data_source: "compliance_manager"
  
  # Performance settings
  performance:
    max_businesses_per_check: 100
    max_audit_events_per_request: 1000
    max_risk_assessments_per_request: 100
    cache_ttl_seconds: 600
    batch_size: 50
  
  # Security settings
  security:
    enable_authentication: true
    api_key_header: "X-API-Key"
    rate_limiting:
      enabled: true
      requests_per_minute: 50
      burst_size: 10
    
    # Data encryption
    encryption:
      enabled: true
      algorithm: "AES-256-GCM"
      key_rotation_days: 30
    
    # Audit trail security
    audit_security:
      immutable_logs: true
      digital_signatures: true
      hash_chain_verification: true
      access_logging: true
